from pathlib import Path
import pandas as pd


def main():
    root = Path(__file__).resolve().parents[1]

    rows = [
        ["submission_leakage", "Raw/test-generated artifacts accidentally omitted or mixed", "Chronological split policy + RUNBOOK + final_definitions.md"],
        ["orbit_cycle_confounding", "Periodic thermal structure masks faults", "Baseline-2, proposed method, Week07/08/09 ablations"],
        ["threshold_bias", "Thresholds may favor recall over FAB", "Trade-off plots + threshold logging"],
        ["label_ambiguity", "Event matching could be interpreted differently", "final_definitions.md"],
        ["nuisance_alarms", "Noise and missingness inflate false alarms", "Week09 robustness results"],
        ["non_reproducible_runs", "Seeds/configs not frozen", "Frozen YAML configs + repro_manifest.csv"],
        ["hidden_dependencies", "Project may fail in fresh environment", "week10_dryrun_check.py"],
        ["missing_artifacts", "Important outputs not generated by script", "week11_repro_audit.csv"],
    ]

    df = pd.DataFrame(rows, columns=["risk_id", "risk_description", "mitigation_or_guardrail"])
    out = root / "docs" / "risk_register.csv"
    df.to_csv(out, index=False)

    print("Week11 risk register written to:", out)


if __name__ == "__main__":
    main()